export const environment = {
  getAllapiUrl: 'https://appointmentservice.bt.skillassure.com/appointment/',
  domain: 'https://appointmentservice.bt.skillassure.com/appointment/',
  vetdomain:'https://vetservice.bt.skillassure.com/api',
  petdomain:'https://petservice.bt.skillassure.com/pet',
  domain1: 'http://localhost:8099/appointment/',
  vet: 'https://vetservice.bt.skillassure.com/api/vet',
  pet: 'https://apigateway.bt.skillassure.com/pet/pet/',
  pet3: 'https://petservice.bt.skillassure.com/pet/',
  pet2: 'https://petservice.bt.skillassure.com/pet/getpetByParentId/',
  clinic: 'https://vetservice.bt.skillassure.com/api/vet/clinic',
  cognito: {
    userPoolId: 'ap-south-1_CIQdUFlbG',
    userPoolWebClientId: '5rns74g3hqve13dmpfctgblcl8',
  },
  production: true,
  DataUrl: 'https://account.bt.skillassure.com/credentials/savecredentials',
  PetURL: `https://petservice.bt.skillassure.com/pet`,
  CredURL: 'https://account.bt.skillassure.com/credentials/getall',
};
